### ISSUE TITLE
Edit beast

### ISSUE THREAD

**Issue by narolan** [narolan/dnd-cards#4]

**Comment by mip29** [comment]
Ik zou hier enkel zelf toegevoegde monsters editable maken. We kunnen later een feature toevoegen om van een bestaand handboek monster, een kopie te maken, dat ze dan zelf kunnen aanpassen.

**Comment by narolan** [comment]
Dat brengt wel even extra moeilijkheden met zich mee. Er is namelijk nog geen onderscheid tussen zelf aangemaakte en PHB-monsters. Voorlopig laat ik dat er dus uit, maar feel free om dat als extra issue/bug toe te voegen.

**Comment by narolan** [comment]
@mip29 kunt gij ne keer kijken wat ge er van vindt en feedback geven?
